server:
  port: 9527

spring:
  application:
    name: Cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利磯服务名进行路由

      routes:
        - id: payment_ routh #payment_ route #路由的ID,设有固定规则但要求唯一, 建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #lb表示load balance
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的进行路由

        - id: payment_ routh2 #ayment_ route   #路由的ID，没有固定规则但要求唯一建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/port #断言,路径相匹配的进行路由


eureka :
  instance:
    hostname: Cloud-gateway-service
  client: #服务超供都provider生册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
