server :
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tyleryq/springcloud-config.git #GitHub上面的git仓库名字
          ###搜索目录
          search-paths:
            - springcloud-config
      ###读取分支
      label: master


  #rabbitmq相关配置15672 是web管理界面的端口; 5672 是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672  #rabbitmq端口
    username: guest
    password: guest



eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负裁均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus辟新配置的端点
    web:
      exposure:
        include: "bus-refresh"
