server :
  port: 9006

spring:
  application:
    name: customer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}



